# ==== Reproducibility ====
seed: 42

# ==== Paths ====
paths:
  data_dir: data                  # where your CSVs live
  reports_dir: reports            # where outputs are written
  figures_dir: reports/figures
  tables_dir: reports/tables

# ==== Data files (relative to paths.data_dir) ====
data:
  vix_file: vix.csv               # columns: date,vix
  vvix_file: vvix.csv             # optional: date,vvix
  vx_file: vx.csv                 # columns: date,vx1,vx2,vx3,vx4
  spy_tr_file: spy_tr.csv         # columns: date,spy_tr (TR index, any base)
  strict: true # <— set True to REQUIRE real files, False to allow synthetic fallback
  required: ["vix", "spy_tr"]   # which logical datasets must exist; vvix stays optional by default
# ==== Feature engineering ====
features:
  # Source columns the pipeline will try to build z-scores for.
  # If a column is missing in your data, it will be skipped gracefully.
  #use_columns: [spy_tr,ret,rv20 ,vix, vvix, vx1, vx2, vx3, basis1, slope12, slope13, curvature, dvix_5, dvix_20, rv20]
  use_columns: [spy_tr, ret,rv20,vix,dvix_5,dvix_20,rv20]
  rolling_zscore_window: 1260     # ~5y of trading days
  fill_method: ffill               # future: not used yet (placeholder)

# ==== State model ====
states:
  method: kmeans                  # (kmeans | hmm) — we’ve implemented kmeans
  k: 4
  refit_cadence_days: 21          # future: monthly re-cluster (placeholder)
  min_history_days: 504           # future: require 2y before labeling (placeholder)
  labels: ["carry_contango", "flat", "stress_backwardation", "convex_stress"]

# ==== Hedge policy ====
policy:
  annual_budget: 0.02             # 2%/yr premium budget
  hedge_states: ["stress_backwardation", "convex_stress"]  # turn on only in these states
  tenor_days: 126                 # ~6 months
  moneyness_pct: -0.10            # 10% OTM (negative means put strike below spot)
  trigger:
    type: simple
    rules:
      require_negative_slope12: true   # vx2 - vx1 < 0
      require_vix_z_gt: 0.5            # VIX above its 5y rolling mean by 0.5σ
      require_vvix_z_gt: 0.0           # VVIX above average (ignored if vvix missing)

# ==== Costs (very simplified) ====
costs:
  option_bid_ask_bps: 0.0015      # ~15 bps of notional
  spy_commission_bps: 0.0001

# ==== Backtest window & mechanics ====
backtest:
  start: 1990-01-01               # you have data back to 1990
  end: 2025-12-31
  initial_nav: 100.0
  rebalance_cadence_days: 21      # monthly-ish re-hedge

# ==== Evaluation ====
evaluation:
  es_alpha: 0.95                  # ES95
  es_alpha_tail: 0.99             # ES99
  utility_gamma_list: [2, 4, 6]   # future: utility calc hook

# ==== Output controls ====
output:
  save_figures: true
  save_tables: true
  verbose: true
